package: ynewsletter
version: '1.2'
author: Jan Kristinus
supportpage: www.github.org/yakamara/redaxo_ynewsletter

page:
    title: 'translate:ynewsletter_send'
    pjax: false
    perm: ynewsletter[]
    block: ynewsletter
    icon: rex-icon fa-hand-spock-o
    subpages:
        send:
            title: 'translate:ynewsletter_send'

requires:
    packages:
        yform: '^3'
    redaxo: '^5.7'

