package: ynewsletter
version: '1.5'
author: Jan Kristinus
supportpage: www.github.com/yakamara/redaxo_ynewsletter

page:
    title: 'translate:ynewsletter'
    pjax: false
    perm: ynewsletter[]
    icon: rex-icon rex-icon-envelope
    subpages:
        newsletter:
            title: 'translate:ynewsletter_newsletter'
            subPath: pages/data_edit.php
            yformTable: rex_ynewsletter
        group:
            title: 'translate:ynewsletter_group'
            perm: admin[]
            subPath: pages/data_edit.php
            yformTable: rex_ynewsletter_group
        exclusionlist:
            title: 'translate:ynewsletter_exclusionlist'
            subPath: pages/data_edit.php
            yformTable: rex_ynewsletter_exclusionlist
        log:
            title: 'translate:ynewsletter_log'
            subPath: pages/data_edit.php
            yformTable: rex_ynewsletter_log
        send_test:
            title: 'translate:ynewsletter_send_test'
        send:
            title: 'translate:ynewsletter_send'
        readme:
            title: 'translate:readme'
            icon: rex-icon fa-info-circle
            itemclass: pull-right

requires:
    packages:
        yrewrite: '^2'
    redaxo: '^5.7'

